#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  mapperLocations: classpath:com/erhui/official/mapper/**/*.xml
  type-aliases-package: com.erhui.official.domain
management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: "*"
        exclude: env
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true