#开发配置
spring:
  datasource:
    url: jdbc:mysql://rm-wz9z0ji8a2yfyr6cwro.mysql.rds.aliyuncs.com:3306/erhui_official?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: developer
    password: Erhui001
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    root: info
    org:
      mybatis: debug
      apache:
        ibatis: debug